apiVersion: v1
kind: Service
metadata:
  name: gitlab-nodeport
  labels:
    app: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - name: gitlab
      port: 80
      targetPort: 31444
---